name: ubuntu
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - uses: fastai/workflows/ssh@master
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        key_file: id_ecdsa

#     - uses: actions/checkout@v2
#     - run: source script-linux.sh

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@master